"""initial database schema

Revision ID: b1ed3a826166
Revises: 
Create Date: 2026-08-14 20:21:00.369270

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.db.base

revision: str = 'b1ed3a826166'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_table('learning_goals',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_mastery_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_mastery_threshold BETWEEN 0 AND 100', name=op.f('ck_learning_goals_mastery_threshold_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goals')),
    sa.UniqueConstraint('code', name=op.f('uq_learning_goals_code'))
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active IN (0, 1)', name=op.f('ck_plans_active_boolean')),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_plans_price_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320, collation='utf8mb4_0900_ai_ci'), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('ai_prompt_versions',
    sa.Column('prompt_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'retired')", name=op.f('ck_ai_prompt_versions_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ai_prompt_versions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_prompt_versions'))
    )
    op.create_index('uq_ai_prompt_versions_key_version', 'ai_prompt_versions', ['prompt_key', 'version'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.db.base.GUID(), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('content_reviews',
    sa.Column('reviewer_id', app.db.base.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.db.base.GUID(), nullable=False),
    sa.Column('review_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_type IN ('video_segment', 'assessment_question', 'resource', 'taxonomy')", name=op.f('ck_content_reviews_review_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'changes_requested')", name=op.f('ck_content_reviews_status_allowed')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_content_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_reviews'))
    )
    op.create_index('ix_content_reviews_entity_status', 'content_reviews', ['entity_type', 'entity_id', 'status'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('learning_style', sa.String(length=30), nullable=True),
    sa.Column('learning_speed', sa.String(length=20), nullable=True),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_study_period', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("learning_speed IN ('fast', 'moderate', 'slow')", name=op.f('ck_learner_profiles_learning_speed_allowed')),
    sa.CheckConstraint("learning_style IN ('visual', 'reading', 'practice', 'mixed')", name=op.f('ck_learner_profiles_learning_style_allowed')),
    sa.CheckConstraint("preferred_study_period IN ('morning', 'afternoon', 'evening', 'late_night')", name=op.f('ck_learner_profiles_study_period_allowed')),
    sa.CheckConstraint('preferred_session_minutes IS NULL OR preferred_session_minutes > 0', name=op.f('ck_learner_profiles_session_minutes_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_learner_profiles_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('revision_due', 'mastery_achieved', 'streak', 'assessment', 'learning_path', 'system')", name=op.f('ck_notifications_type_allowed')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streaks')),
    sa.UniqueConstraint('user_id', name=op.f('uq_streaks_user_id'))
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subjects_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('slug', name=op.f('uq_subjects_slug'))
    )
    op.create_index('ix_subjects_is_published', 'subjects', ['is_published'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('plan_id', app.db.base.GUID(), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('provider_subscription_id', name=op.f('uq_subscriptions_provider_subscription_id'))
    )
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('achievement_id', app.db.base.GUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements'))
    )
    op.create_index('uq_user_achievements_user_achievement', 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('role_id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('xp_transactions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_xp_transactions_amount_nonzero')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_transactions'))
    )
    op.create_index('ix_xp_transactions_user_created', 'xp_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('ai_generations',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version_id', app.db.base.GUID(), nullable=False),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("generation_type IN ('assessment_question', 'quiz_question', 'video_segmentation', 'recommendation', 'tutor_response', 'insight', 'summary', 'taxonomy_tagging')", name=op.f('ck_ai_generations_generation_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name=op.f('ck_ai_generations_status_allowed')),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_ai_generations_estimated_cost_nonnegative')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_ai_generations_input_tokens_nonnegative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_ai_generations_latency_nonnegative')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_ai_generations_output_tokens_nonnegative')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['ai_prompt_versions.id'], name=op.f('fk_ai_generations_prompt_version_id_ai_prompt_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    op.create_index('ix_ai_generations_generation_type_created', 'ai_generations', ['generation_type', 'created_at'], unique=False)
    op.create_table('analytics_events',
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('subject_id', app.db.base.GUID(), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', app.db.base.GUID(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_analytics_events_subject_id_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_events_name_occurred', 'analytics_events', ['event_name', 'occurred_at'], unique=False)
    op.create_index('ix_analytics_events_subject_occurred', 'analytics_events', ['subject_id', 'occurred_at'], unique=False)
    op.create_index('ix_analytics_events_user_occurred', 'analytics_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('cohorts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('instructor_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_cohorts_instructor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_cohorts_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts'))
    )
    op.create_index('ix_cohorts_instructor_subject', 'cohorts', ['instructor_id', 'subject_id'], unique=False)
    op.create_table('courses',
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('instructor_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'processing', 'review', 'published', 'archived')", name=op.f('ck_courses_status_allowed')),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name=op.f('ck_courses_estimated_minutes_positive')),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_courses_instructor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_courses_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_index('ix_courses_subject_id', 'courses', ['subject_id'], unique=False)
    op.create_table('daily_learning_metrics',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('study_seconds', sa.Integer(), nullable=False),
    sa.Column('concepts_practiced', sa.Integer(), nullable=False),
    sa.Column('concepts_mastered', sa.Integer(), nullable=False),
    sa.Column('quiz_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('video_seconds_watched', sa.Integer(), nullable=False),
    sa.Column('video_seconds_skipped', sa.Integer(), nullable=False),
    sa.Column('tutor_interactions', sa.Integer(), nullable=False),
    sa.Column('time_saved_seconds', sa.Integer(), nullable=False),
    sa.Column('streak_day', sa.Integer(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('concepts_mastered >= 0', name=op.f('ck_daily_learning_metrics_concepts_mastered_nonnegative')),
    sa.CheckConstraint('concepts_practiced >= 0', name=op.f('ck_daily_learning_metrics_concepts_practiced_nonnegative')),
    sa.CheckConstraint('correct_answers >= 0', name=op.f('ck_daily_learning_metrics_correct_answers_nonnegative')),
    sa.CheckConstraint('quiz_attempts >= 0', name=op.f('ck_daily_learning_metrics_quiz_attempts_nonnegative')),
    sa.CheckConstraint('study_seconds >= 0', name=op.f('ck_daily_learning_metrics_study_seconds_nonnegative')),
    sa.CheckConstraint('time_saved_seconds >= 0', name=op.f('ck_daily_learning_metrics_time_saved_nonnegative')),
    sa.CheckConstraint('tutor_interactions >= 0', name=op.f('ck_daily_learning_metrics_tutor_interactions_nonnegative')),
    sa.CheckConstraint('video_seconds_skipped >= 0', name=op.f('ck_daily_learning_metrics_video_skipped_nonnegative')),
    sa.CheckConstraint('video_seconds_watched >= 0', name=op.f('ck_daily_learning_metrics_video_watched_nonnegative')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_daily_learning_metrics_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_learning_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_learning_metrics'))
    )
    op.create_index('ix_daily_learning_metrics_user_date', 'daily_learning_metrics', ['user_id', 'metric_date'], unique=False)
    op.create_index('uq_daily_learning_metrics_user_subject_date', 'daily_learning_metrics', ['user_id', 'subject_id', 'metric_date'], unique=True)
    op.create_table('learner_subjects',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('learning_goal_id', app.db.base.GUID(), nullable=False),
    sa.Column('target_mastery', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name=op.f('ck_learner_subjects_status_allowed')),
    sa.CheckConstraint('target_mastery BETWEEN 0 AND 100', name=op.f('ck_learner_subjects_target_mastery_range')),
    sa.ForeignKeyConstraint(['learning_goal_id'], ['learning_goals.id'], name=op.f('fk_learner_subjects_learning_goal_id_learning_goals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_learner_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_subjects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_subjects'))
    )
    op.create_index('ix_learner_subjects_user_subject', 'learner_subjects', ['user_id', 'subject_id'], unique=False)
    op.create_index('ix_learner_subjects_user_subject_status', 'learner_subjects', ['user_id', 'subject_id', 'status'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.db.base.GUID(), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name=op.f('ck_payment_transactions_amount_nonnegative')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payment_transactions_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('provider_transaction_id', name=op.f('uq_payment_transactions_provider_transaction_id'))
    )
    op.create_index('ix_payment_transactions_user_created', 'payment_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('study_sessions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=40), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('assessment', 'lesson', 'video', 'practice', 'tutor', 'revision', 'project')", name=op.f('ck_study_sessions_activity_type_allowed')),
    sa.CheckConstraint('duration_seconds >= 0', name=op.f('ck_study_sessions_duration_nonnegative')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_study_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index('ix_study_sessions_user_started', 'study_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('topics',
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('parent_topic_id', app.db.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], name=op.f('fk_topics_parent_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index('ix_topics_subject_id', 'topics', ['subject_id'], unique=False)
    op.create_index('uq_topics_subject_slug', 'topics', ['subject_id', 'slug'], unique=True)
    op.create_table('assessments',
    sa.Column('learner_subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('target_concepts', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assessment_type IN ('diagnostic', 'adaptive_quiz', 'revision', 'practice', 'final')", name=op.f('ck_assessments_assessment_type_allowed')),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'completed', 'abandoned')", name=op.f('ck_assessments_status_allowed')),
    sa.ForeignKeyConstraint(['learner_subject_id'], ['learner_subjects.id'], name=op.f('fk_assessments_learner_subject_id_learner_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index('ix_assessments_learner_subject_id', 'assessments', ['learner_subject_id'], unique=False)
    op.create_table('certificates',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('learner_subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('verification_token', sa.String(length=120), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 100', name=op.f('ck_certificates_mastery_score_range')),
    sa.ForeignKeyConstraint(['learner_subject_id'], ['learner_subjects.id'], name=op.f('fk_certificates_learner_subject_id_learner_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('certificate_number', name=op.f('uq_certificates_certificate_number')),
    sa.UniqueConstraint('verification_token', name=op.f('uq_certificates_verification_token'))
    )
    op.create_index('uq_certificates_learner_subject', 'certificates', ['learner_subject_id'], unique=True)
    op.create_table('cohort_members',
    sa.Column('cohort_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_members_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cohort_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id', 'user_id', name=op.f('pk_cohort_members'))
    )
    op.create_table('concepts',
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('topic_id', app.db.base.GUID(), nullable=True),
    sa.Column('parent_concept_id', app.db.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_baseline', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty_baseline IS NULL OR difficulty_baseline BETWEEN 0 AND 100', name=op.f('ck_concepts_difficulty_baseline_range')),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concepts.id'], name=op.f('fk_concepts_parent_concept_id_concepts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_concepts_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_concepts_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    op.create_index('ix_concepts_parent_concept_id', 'concepts', ['parent_concept_id'], unique=False)
    op.create_index('ix_concepts_subject_id', 'concepts', ['subject_id'], unique=False)
    op.create_index('ix_concepts_topic_id', 'concepts', ['topic_id'], unique=False)
    op.create_table('course_modules',
    sa.Column('course_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_modules_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_modules'))
    )
    op.create_index('ix_course_modules_course_sort', 'course_modules', ['course_id', 'sort_order'], unique=False)
    op.create_table('enrollments',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('course_id', app.db.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    op.create_index('uq_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=True)
    op.create_table('learning_paths',
    sa.Column('learner_subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('generated_from_mastery_version', app.db.base.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'completed', 'superseded')", name=op.f('ck_learning_paths_status_allowed')),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes >= 0', name=op.f('ck_learning_paths_estimated_minutes_nonnegative')),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name=op.f('ck_learning_paths_progress_percent_range')),
    sa.ForeignKeyConstraint(['learner_subject_id'], ['learner_subjects.id'], name=op.f('fk_learning_paths_learner_subject_id_learner_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_paths'))
    )
    op.create_index('ix_learning_paths_learner_subject_status', 'learning_paths', ['learner_subject_id', 'status'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=True),
    sa.Column('concept_id', app.db.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_ai_conversations_concept_id_concepts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_ai_conversations_subject_id_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    op.create_index('ix_ai_conversations_user_updated', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('assessment_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('answered_items', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned', 'expired')", name=op.f('ck_assessment_attempts_status_allowed')),
    sa.CheckConstraint('answered_items <= total_items', name=op.f('ck_assessment_attempts_answered_not_over_total')),
    sa.CheckConstraint('answered_items >= 0', name=op.f('ck_assessment_attempts_answered_items_nonnegative')),
    sa.CheckConstraint('total_items >= 0', name=op.f('ck_assessment_attempts_total_items_nonnegative')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_attempts_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts'))
    )
    op.create_index('ix_assessment_attempts_user_status', 'assessment_attempts', ['user_id', 'status'], unique=False)
    op.create_table('concept_analytics_snapshots',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('study_seconds', sa.Integer(), nullable=False),
    sa.Column('video_seconds', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy BETWEEN 0 AND 100', name=op.f('ck_concept_analytics_snapshots_accuracy_range')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_concept_analytics_snapshots_attempts_nonnegative')),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name=op.f('ck_concept_analytics_snapshots_confidence_score_range')),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 100', name=op.f('ck_concept_analytics_snapshots_mastery_score_range')),
    sa.CheckConstraint('revision_count >= 0', name=op.f('ck_concept_analytics_snapshots_revision_count_nonnegative')),
    sa.CheckConstraint('study_seconds >= 0', name=op.f('ck_concept_analytics_snapshots_study_seconds_nonnegative')),
    sa.CheckConstraint('video_seconds >= 0', name=op.f('ck_concept_analytics_snapshots_video_seconds_nonnegative')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_concept_analytics_snapshots_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_concept_analytics_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_analytics_snapshots'))
    )
    op.create_index('ix_concept_analytics_user_concept_date', 'concept_analytics_snapshots', ['user_id', 'concept_id', 'snapshot_date'], unique=False)
    op.create_index('uq_concept_analytics_user_concept_date', 'concept_analytics_snapshots', ['user_id', 'concept_id', 'snapshot_date'], unique=True)
    op.create_table('concept_prerequisites',
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('prerequisite_concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('concept_id <> prerequisite_concept_id', name=op.f('ck_concept_prerequisites_not_self_reference')),
    sa.CheckConstraint('strength IS NULL OR strength BETWEEN 0 AND 100', name=op.f('ck_concept_prerequisites_strength_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_concept_prerequisites_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['concepts.id'], name=op.f('fk_concept_prerequisites_prerequisite_concept_id_concepts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'prerequisite_concept_id', name=op.f('pk_concept_prerequisites'))
    )
    op.create_index('ix_concept_prerequisites_concept_id', 'concept_prerequisites', ['concept_id'], unique=False)
    op.create_index('ix_concept_prerequisites_prerequisite_id', 'concept_prerequisites', ['prerequisite_concept_id'], unique=False)
    op.create_table('learner_concept_mastery',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mastery_state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('last_revised_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('decay_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mastery_state IN ('unknown', 'weak', 'partial', 'mastered')", name=op.f('ck_learner_concept_mastery_mastery_state_allowed')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_learner_concept_mastery_attempts_nonnegative')),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name=op.f('ck_learner_concept_mastery_confidence_score_range')),
    sa.CheckConstraint('correct_attempts <= attempts', name=op.f('ck_learner_concept_mastery_correct_not_over_attempts')),
    sa.CheckConstraint('correct_attempts >= 0', name=op.f('ck_learner_concept_mastery_correct_attempts_nonnegative')),
    sa.CheckConstraint('decay_score IS NULL OR decay_score BETWEEN 0 AND 100', name=op.f('ck_learner_concept_mastery_decay_score_range')),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 100', name=op.f('ck_learner_concept_mastery_mastery_score_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_learner_concept_mastery_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_learner_concept_mastery_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_concept_mastery_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_concept_mastery'))
    )
    op.create_index('ix_mastery_user_state', 'learner_concept_mastery', ['user_id', 'mastery_state'], unique=False)
    op.create_index('ix_mastery_user_subject', 'learner_concept_mastery', ['user_id', 'subject_id'], unique=False)
    op.create_index('uq_mastery_user_concept', 'learner_concept_mastery', ['user_id', 'concept_id'], unique=True)
    op.create_table('learning_path_steps',
    sa.Column('learning_path_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mastery_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('prerequisite_status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("prerequisite_status IN ('satisfied', 'scheduled_before', 'blocked')", name=op.f('ck_learning_path_steps_prerequisite_status_allowed')),
    sa.CheckConstraint("status IN ('locked', 'ready', 'in_progress', 'mastered', 'needs_revision')", name=op.f('ck_learning_path_steps_status_allowed')),
    sa.CheckConstraint('mastery_threshold BETWEEN 0 AND 100', name=op.f('ck_learning_path_steps_mastery_threshold_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_learning_path_steps_concept_id_concepts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], name=op.f('fk_learning_path_steps_learning_path_id_learning_paths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_steps'))
    )
    op.create_index('ix_learning_path_steps_path_sequence', 'learning_path_steps', ['learning_path_id', 'sequence_number'], unique=False)
    op.create_table('lessons',
    sa.Column('module_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name=op.f('ck_lessons_estimated_minutes_positive')),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_lessons_module_id_course_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index('ix_lessons_module_sort', 'lessons', ['module_id', 'sort_order'], unique=False)
    op.create_table('mastery_events',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', app.db.base.GUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("event_type IN ('assessment_answered', 'quiz_submitted', 'practice_completed', 'video_watched', 'tutor_interaction', 'revision_completed', 'mastery_decay')", name=op.f('ck_mastery_events_event_type_allowed')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_mastery_events_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_mastery_events_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mastery_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_mastery_events_idempotency_key'))
    )
    op.create_index('ix_mastery_events_processed_at', 'mastery_events', ['processed_at'], unique=False)
    op.create_index('ix_mastery_events_user_concept', 'mastery_events', ['user_id', 'concept_id'], unique=False)
    op.create_table('questions',
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('answer_data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('ai_generation_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('mcq', 'true_false', 'short_answer', 'coding', 'multiple_select')", name=op.f('ck_questions_question_type_allowed')),
    sa.CheckConstraint('difficulty IS NULL OR difficulty BETWEEN 0 AND 100', name=op.f('ck_questions_difficulty_range')),
    sa.ForeignKeyConstraint(['ai_generation_id'], ['ai_generations.id'], name=op.f('fk_questions_ai_generation_id_ai_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_questions_concept_id_concepts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index('ix_questions_concept_id', 'questions', ['concept_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', app.db.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant', 'tool')", name=op.f('ck_ai_messages_role_allowed')),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index('ix_ai_messages_conversation_created', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('assessment_items',
    sa.Column('assessment_id', app.db.base.GUID(), nullable=False),
    sa.Column('question_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('selected_difficulty', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('selected_difficulty IS NULL OR selected_difficulty BETWEEN 0 AND 100', name=op.f('ck_assessment_items_selected_difficulty_range')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_items_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_assessment_items_concept_id_concepts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_assessment_items_question_id_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_items'))
    )
    op.create_index('ix_assessment_items_assessment_sequence', 'assessment_items', ['assessment_id', 'sequence_number'], unique=False)
    op.create_table('mastery_history',
    sa.Column('learner_concept_mastery_id', app.db.base.GUID(), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=False),
    sa.Column('new_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("new_state IN ('unknown', 'weak', 'partial', 'mastered')", name=op.f('ck_mastery_history_new_state_allowed')),
    sa.CheckConstraint("previous_state IN ('unknown', 'weak', 'partial', 'mastered')", name=op.f('ck_mastery_history_previous_state_allowed')),
    sa.CheckConstraint("reason IN ('assessment', 'quiz', 'practice', 'video_watch', 'tutor_interaction', 'decay', 'manual_review')", name=op.f('ck_mastery_history_reason_allowed')),
    sa.CheckConstraint('new_score BETWEEN 0 AND 100', name=op.f('ck_mastery_history_new_score_range')),
    sa.CheckConstraint('previous_score BETWEEN 0 AND 100', name=op.f('ck_mastery_history_previous_score_range')),
    sa.ForeignKeyConstraint(['learner_concept_mastery_id'], ['learner_concept_mastery.id'], name=op.f('fk_mastery_history_learner_concept_mastery_id_learner_concept_mastery'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_history'))
    )
    op.create_index('ix_mastery_history_mastery_created', 'mastery_history', ['learner_concept_mastery_id', 'created_at'], unique=False)
    op.create_table('question_options',
    sa.Column('question_id', app.db.base.GUID(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('option_key', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options'))
    )
    op.create_index('ix_question_options_question_sort', 'question_options', ['question_id', 'sort_order'], unique=False)
    op.create_table('resources',
    sa.Column('lesson_id', app.db.base.GUID(), nullable=True),
    sa.Column('subject_id', app.db.base.GUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_by', app.db.base.GUID(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type IN ('video', 'notes', 'documentation', 'coding_exercise', 'project', 'flashcard', 'article')", name=op.f('ck_resources_resource_type_allowed')),
    sa.CheckConstraint('quality_score IS NULL OR quality_score BETWEEN 0 AND 100', name=op.f('ck_resources_quality_score_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_resources_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_resources_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_resources_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index('ix_resources_lesson_id', 'resources', ['lesson_id'], unique=False)
    op.create_index('ix_resources_resource_type', 'resources', ['resource_type'], unique=False)
    op.create_index('ix_resources_subject_id', 'resources', ['subject_id'], unique=False)
    op.create_table('revision_schedule',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('mastery_id', app.db.base.GUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('interval_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('last_result', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ease_factor > 0', name=op.f('ck_revision_schedule_ease_factor_positive')),
    sa.CheckConstraint('interval_days >= 0', name=op.f('ck_revision_schedule_interval_days_nonnegative')),
    sa.CheckConstraint('repetition_count >= 0', name=op.f('ck_revision_schedule_repetition_count_nonnegative')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_revision_schedule_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mastery_id'], ['learner_concept_mastery.id'], name=op.f('fk_revision_schedule_mastery_id_learner_concept_mastery'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revision_schedule_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_schedule'))
    )
    op.create_index('ix_revision_schedule_user_due', 'revision_schedule', ['user_id', 'due_at'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('attempt_id', app.db.base.GUID(), nullable=False),
    sa.Column('assessment_item_id', app.db.base.GUID(), nullable=False),
    sa.Column('answer_data', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_rating', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_rating IS NULL OR confidence_rating BETWEEN 1 AND 5', name=op.f('ck_assessment_responses_confidence_rating_range')),
    sa.CheckConstraint('response_time_ms IS NULL OR response_time_ms >= 0', name=op.f('ck_assessment_responses_response_time_nonnegative')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_assessment_responses_score_range')),
    sa.ForeignKeyConstraint(['assessment_item_id'], ['assessment_items.id'], name=op.f('fk_assessment_responses_assessment_item_id_assessment_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_assessment_responses_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_responses'))
    )
    op.create_index('ix_assessment_responses_attempt_id', 'assessment_responses', ['attempt_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('resource_id', app.db.base.GUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recommendation_type IN ('learn', 'practice', 'revision', 'video', 'reading', 'project')", name=op.f('ck_recommendations_recommendation_type_allowed')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_recommendations_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_recommendations_resource_id_resources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_user_concept', 'recommendations', ['user_id', 'concept_id'], unique=False)
    op.create_table('resource_concepts',
    sa.Column('resource_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('relevance_score IS NULL OR relevance_score BETWEEN 0 AND 100', name=op.f('ck_resource_concepts_relevance_score_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_resource_concepts_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_concepts_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'concept_id', name=op.f('pk_resource_concepts'))
    )
    op.create_index('ix_resource_concepts_concept_id', 'resource_concepts', ['concept_id'], unique=False)
    op.create_table('videos',
    sa.Column('resource_id', app.db.base.GUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=30), nullable=True),
    sa.Column('transcript_status', sa.String(length=30), nullable=False),
    sa.Column('segmentation_status', sa.String(length=30), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_videos_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    sa.UniqueConstraint('resource_id', name=op.f('uq_videos_resource_id'))
    )
    op.create_table('recommendation_feedback',
    sa.Column('recommendation_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('feedback', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feedback IN ('helpful', 'not_helpful', 'dismissed', 'completed')", name=op.f('ck_recommendation_feedback_feedback_allowed')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_feedback_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedback'))
    )
    op.create_index('ix_recommendation_feedback_recommendation_id', 'recommendation_feedback', ['recommendation_id'], unique=False)
    op.create_table('video_segments',
    sa.Column('video_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('start_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', app.db.base.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited')", name=op.f('ck_video_segments_review_status_allowed')),
    sa.CheckConstraint("source IN ('ai', 'instructor', 'hybrid')", name=op.f('ck_video_segments_source_allowed')),
    sa.CheckConstraint('ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 100', name=op.f('ck_video_segments_ai_confidence_range')),
    sa.CheckConstraint('end_seconds > start_seconds', name=op.f('ck_video_segments_end_after_start')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_video_segments_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_segments_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_segments'))
    )
    op.create_index('ix_video_segments_video_start', 'video_segments', ['video_id', 'start_seconds'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('resource_id', app.db.base.GUID(), nullable=True),
    sa.Column('video_id', app.db.base.GUID(), nullable=True),
    sa.Column('segment_id', app.db.base.GUID(), nullable=True),
    sa.Column('position_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position_seconds IS NULL OR position_seconds >= 0', name=op.f('ck_bookmarks_position_nonnegative')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_bookmarks_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], name=op.f('fk_bookmarks_segment_id_video_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_bookmarks_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks'))
    )
    op.create_index('ix_bookmarks_user_created', 'bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('resource_id', app.db.base.GUID(), nullable=True),
    sa.Column('video_id', app.db.base.GUID(), nullable=True),
    sa.Column('segment_id', app.db.base.GUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position_seconds IS NULL OR position_seconds >= 0', name=op.f('ck_notes_position_nonnegative')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_notes_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], name=op.f('fk_notes_segment_id_video_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_notes_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_user_updated', 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_table('video_segment_concepts',
    sa.Column('segment_id', app.db.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.base.GUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 100', name=op.f('ck_video_segment_concepts_confidence_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_video_segment_concepts_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], name=op.f('fk_video_segment_concepts_segment_id_video_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'concept_id', name=op.f('pk_video_segment_concepts'))
    )
    op.create_index('ix_video_segment_concepts_concept_id', 'video_segment_concepts', ['concept_id'], unique=False)
    op.create_table('video_watch_events',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('video_id', app.db.base.GUID(), nullable=False),
    sa.Column('segment_id', app.db.base.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('position_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('session_id', app.db.base.GUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.CheckConstraint("event_type IN ('started', 'played', 'paused', 'completed', 'seeked', 'skipped', 'rewatched')", name=op.f('ck_video_watch_events_event_type_allowed')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_video_watch_events_duration_nonnegative')),
    sa.CheckConstraint('position_seconds >= 0', name=op.f('ck_video_watch_events_position_nonnegative')),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], name=op.f('fk_video_watch_events_segment_id_video_segments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_video_watch_events_session_id_study_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_video_watch_events_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_watch_events_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_watch_events'))
    )
    op.create_index('ix_video_watch_events_user_occurred', 'video_watch_events', ['user_id', 'occurred_at'], unique=False)
    op.create_index('ix_video_watch_events_video_position', 'video_watch_events', ['video_id', 'position_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_watch_events_video_position', table_name='video_watch_events')
    op.drop_index('ix_video_watch_events_user_occurred', table_name='video_watch_events')
    op.drop_table('video_watch_events')
    op.drop_index('ix_video_segment_concepts_concept_id', table_name='video_segment_concepts')
    op.drop_table('video_segment_concepts')
    op.drop_index('ix_notes_user_updated', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_bookmarks_user_created', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index('ix_video_segments_video_start', table_name='video_segments')
    op.drop_table('video_segments')
    op.drop_index('ix_recommendation_feedback_recommendation_id', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_table('videos')
    op.drop_index('ix_resource_concepts_concept_id', table_name='resource_concepts')
    op.drop_table('resource_concepts')
    op.drop_index('ix_recommendations_user_concept', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_assessment_responses_attempt_id', table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index('ix_revision_schedule_user_due', table_name='revision_schedule')
    op.drop_table('revision_schedule')
    op.drop_index('ix_resources_subject_id', table_name='resources')
    op.drop_index('ix_resources_resource_type', table_name='resources')
    op.drop_index('ix_resources_lesson_id', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_question_options_question_sort', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_mastery_history_mastery_created', table_name='mastery_history')
    op.drop_table('mastery_history')
    op.drop_index('ix_assessment_items_assessment_sequence', table_name='assessment_items')
    op.drop_table('assessment_items')
    op.drop_index('ix_ai_messages_conversation_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_questions_concept_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_mastery_events_user_concept', table_name='mastery_events')
    op.drop_index('ix_mastery_events_processed_at', table_name='mastery_events')
    op.drop_table('mastery_events')
    op.drop_index('ix_lessons_module_sort', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_learning_path_steps_path_sequence', table_name='learning_path_steps')
    op.drop_table('learning_path_steps')
    op.drop_index('uq_mastery_user_concept', table_name='learner_concept_mastery')
    op.drop_index('ix_mastery_user_subject', table_name='learner_concept_mastery')
    op.drop_index('ix_mastery_user_state', table_name='learner_concept_mastery')
    op.drop_table('learner_concept_mastery')
    op.drop_index('ix_concept_prerequisites_prerequisite_id', table_name='concept_prerequisites')
    op.drop_index('ix_concept_prerequisites_concept_id', table_name='concept_prerequisites')
    op.drop_table('concept_prerequisites')
    op.drop_index('uq_concept_analytics_user_concept_date', table_name='concept_analytics_snapshots')
    op.drop_index('ix_concept_analytics_user_concept_date', table_name='concept_analytics_snapshots')
    op.drop_table('concept_analytics_snapshots')
    op.drop_index('ix_assessment_attempts_user_status', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index('ix_ai_conversations_user_updated', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('ix_learning_paths_learner_subject_status', table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index('uq_enrollments_user_course', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_course_modules_course_sort', table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('ix_concepts_topic_id', table_name='concepts')
    op.drop_index('ix_concepts_subject_id', table_name='concepts')
    op.drop_index('ix_concepts_parent_concept_id', table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('cohort_members')
    op.drop_index('uq_certificates_learner_subject', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_assessments_learner_subject_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('uq_topics_subject_slug', table_name='topics')
    op.drop_index('ix_topics_subject_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_study_sessions_user_started', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('ix_payment_transactions_user_created', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_learner_subjects_user_subject_status', table_name='learner_subjects')
    op.drop_index('ix_learner_subjects_user_subject', table_name='learner_subjects')
    op.drop_table('learner_subjects')
    op.drop_index('uq_daily_learning_metrics_user_subject_date', table_name='daily_learning_metrics')
    op.drop_index('ix_daily_learning_metrics_user_date', table_name='daily_learning_metrics')
    op.drop_table('daily_learning_metrics')
    op.drop_index('ix_courses_subject_id', table_name='courses')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_cohorts_instructor_subject', table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index('ix_analytics_events_user_occurred', table_name='analytics_events')
    op.drop_index('ix_analytics_events_subject_occurred', table_name='analytics_events')
    op.drop_index('ix_analytics_events_name_occurred', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('ix_ai_generations_generation_type_created', table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index('ix_xp_transactions_user_created', table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_table('user_roles')
    op.drop_index('uq_user_achievements_user_achievement', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_subjects_is_published', table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('streaks')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('learner_profiles')
    op.drop_index('ix_content_reviews_entity_status', table_name='content_reviews')
    op.drop_table('content_reviews')
    op.drop_index('ix_audit_logs_entity_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_ai_prompt_versions_key_version', table_name='ai_prompt_versions')
    op.drop_table('ai_prompt_versions')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('plans')
    op.drop_table('learning_goals')
    op.drop_table('achievements')
    # ### end Alembic commands ###
